/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: ({ colors }) => ({
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      neutral: colors.neutral,
      amber: colors.amber,
      green: colors.green,
      blue: colors.blue,
      lime: colors.lime,
      purple: colors.purple,
      rose: colors.rose,
    }),
    fontFamily: {
      sans: [
        'Ubuntu',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: [
        'ui-serif',
        'Georgia',
        'Cambria',
        '"Times New Roman"',
        'Times',
        'serif',
      ],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
      cursive: ['Finger Paint', 'cursive'],
      atkinson: ['Atkinson Hyperlegible', 'sans-serif'],
      roboto: ['Roboto', 'sans-serif'],
    },
    gridTemplateColumns: {
      'fill-260': 'repeat(auto-fill, 260px)',
      'fill-150': 'repeat(auto-fill, 150px)',
      'fill-200': 'repeat(auto-fill, 200px)',
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
